version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: javier
      WORDPRESS_DB_PASSWORD: Alisal2022
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
   
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: javier
      MYSQL_PASSWORD: Alisal2022
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql


volumes:
  wordpress:
  db:
  
